// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230128140611_AbstractProduct")]
    partial class AbstractProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Domain.ProductDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Membership", b =>
                {
                    b.HasBaseType("Domain.ProductDetails");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("INTEGER");

                    b.ToTable("Domain.Membership", (string)null);
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.HasBaseType("Domain.ProductDetails");

                    b.Property<bool>("IsShipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductType")
                        .HasColumnType("INTEGER");

                    b.ToTable("Domain.Product", (string)null);
                });

            modelBuilder.Entity("Domain.Membership", b =>
                {
                    b.HasOne("Domain.ProductDetails", null)
                        .WithOne()
                        .HasForeignKey("Domain.Membership", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.HasOne("Domain.ProductDetails", null)
                        .WithOne()
                        .HasForeignKey("Domain.Product", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
